apiVersion: v1
kind: Service
metadata:
  name: prepsom-backend-v2-service
spec:
  selector:
    app: prepsom-backend-v2
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8000
  type: LoadBalancer
